export const TODOS_FETCH_REQUESTED = "TODOS_FETCH_REQUESTED";
export const TODOS_FETCH_SUCCEEDED = "TODOS_FETCH_SUCCEEDED";
export const TODOS_FETCH_FAILED = "TODOS_FETCH_FAILED";

export const ADD_TODO_REQUESTED = "ADD_TODO_REQUESTED";
export const ADD_TODO_SUCCEEDED = "ADD_TODO_SUCCEEDED";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";

export const DELETE_TODO_REQUESTED = "DELETE_TODO_REQUESTED";
export const DELETE_TODO_SUCCEEDED = "DELETE_TODO_SUCCEEDED";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";

export const TOGGLE_COMPLETED_REQUESTED = "TOGGLE_COMPLETED_REQUESTED";
export const TOGGLE_COMPLETED_SUCCEEDED = "TOGGLE_COMPLETED_SUCCEEDED";
export const TOGGLE_COMPLETED_FAILED = "TOGGLE_COMPLETED_FAILED";

export const CLEAR_COMPLETED_REQUESTED = "CLEAR_COMPLETED_REQUESTED";
export const CLEAR_COMPLETED_SUCCEEDED = "CLEAR_COMPLETED_SUCCEEDED";
export const CLEAR_COMPLETED_FAILED = "CLEAR_COMPLETED_FAILED";
